version: '3.8'

services:
  python-tf:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    container_name: python-tf
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspaces
      - ./.bashrc:/home/vscode/.bashrc
      - ~/.gitconfig:/home/vscode/.gitconfig:rw
      - ~/.config/gcloud/:/home/.config/gcloud:ro
    command: sleep infinity
