name: Terraform Apply CI

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    name: Terraform Apply Changes
    runs-on: ubuntu-latest

    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json

    steps:

      - name: Decode and write GCP SA key
        run: |
          echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > $GOOGLE_APPLICATION_CREDENTIALS

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run:  |
          cd infra
          terraform init

      - name: Terraform Apply
        run:  |
          cd infra
          terraform apply -auto-approve -no-color
