name: Terraform Apply CI

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    name: Terraform Apply Changes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: infra

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color
        working-directory: infra
